version: "3.3"

services:
    db:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - "POSTGRES_HOST_AUTH_METHOD=trust"

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - db
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        restart: always
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        networks:
            - logging

    server:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                INSTALL_DEV: ${INSTALL_DEV-false}
        depends_on:
            - elasticsearch
        env_file:
            - .env

volumes:
    db-data:

networks: 
    logging: